from __future__ import annotations

import json
from pathlib import Path

import pytest

from scripts import bump_version, validate_release


def write_bump_repo(root: Path, *, changelog_version: str = "0.2.0") -> None:
    (root / "app").mkdir(parents=True)
    (root / "app" / "__init__.py").write_text(
        '__version__ = "0.1.0"\n',
        encoding="utf-8",
    )
    tauri_root = root / "frontend" / "src-tauri"
    tauri_root.mkdir(parents=True)
    (tauri_root / "tauri.conf.json").write_text(
        json.dumps(
            {
                "$schema": "../node_modules/@tauri-apps/cli/config.schema.json",
                "productName": "ResumeCR7",
                "version": "0.1.0",
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    (tauri_root / "Cargo.toml").write_text(
        "\n".join(
            [
                "[package]",
                'name = "resumecr7-desktop"',
                'version = "0.1.0"',
                'description = "ResumeCR7 desktop shell"',
                "",
                "[dependencies]",
                'tauri = { version = "2", features = [] }',
                "",
            ]
        ),
        encoding="utf-8",
    )
    (tauri_root / "Cargo.lock").write_text(
        "\n".join(
            [
                "# This file is automatically @generated by Cargo.",
                "version = 4",
                "",
                "[[package]]",
                'name = "other-package"',
                'version = "0.1.0"',
                "",
                "[[package]]",
                'name = "resumecr7-desktop"',
                'version = "0.1.0"',
                "dependencies = [",
                ' "tauri",',
                "]",
                "",
            ]
        ),
        encoding="utf-8",
    )
    (root / "docs").mkdir()
    (root / "docs" / "CHANGELOG.md").write_text(
        "\n".join(
            [
                "# Changelog",
                "",
                "## [Unreleased]",
                "",
                f"## [{changelog_version}] - 2026-08-09",
                "",
                "### Added",
                "- Release note.",
                "",
                "## [0.1.0] - 2026-07-28",
                "",
                "### Added",
                "- Prior release.",
                "",
            ]
        ),
        encoding="utf-8",
    )


def test_parse_tag_version_rejects_malformed_tag():
    with pytest.raises(bump_version.VersionBumpError, match="vX.Y.Z"):
        bump_version.parse_tag_version("0.2.0")


def test_status_paths_handles_modified_untracked_and_renamed_files():
    status = "\n".join(
        [
            " M docs/CHANGELOG.md",
            "?? scripts/bump_version.py",
            "R  old-name.txt -> new-name.txt",
        ]
    )

    assert bump_version.status_paths(status) == [
        "docs/CHANGELOG.md",
        "scripts/bump_version.py",
        "old-name.txt",
        "new-name.txt",
    ]


def test_apply_version_updates_updates_release_metadata(tmp_path):
    write_bump_repo(tmp_path)

    bump_version.apply_version_updates(tmp_path, "v0.2.0")

    assert validate_release.validate_release("v0.2.0", tmp_path) == "0.2.0"
    assert '__version__ = "0.2.0"' in (tmp_path / "app" / "__init__.py").read_text(
        encoding="utf-8"
    )


def test_apply_version_updates_scopes_cargo_lock_to_desktop_package(tmp_path):
    write_bump_repo(tmp_path)

    bump_version.apply_version_updates(tmp_path, "v0.2.0")

    lock_text = (
        tmp_path / "frontend" / "src-tauri" / "Cargo.lock"
    ).read_text(encoding="utf-8")
    assert 'name = "other-package"\nversion = "0.1.0"' in lock_text
    assert 'name = "resumecr7-desktop"\nversion = "0.2.0"' in lock_text


def test_apply_version_updates_rejects_missing_changelog_release(tmp_path):
    write_bump_repo(tmp_path, changelog_version="0.1.9")

    with pytest.raises(bump_version.VersionBumpError, match="Latest changelog"):
        bump_version.apply_version_updates(tmp_path, "v0.2.0")


def test_apply_version_updates_dry_run_does_not_write_files(tmp_path):
    write_bump_repo(tmp_path)
    app_path = tmp_path / "app" / "__init__.py"
    before = app_path.read_text(encoding="utf-8")

    bump_version.apply_version_updates(tmp_path, "v0.2.0", dry_run=True)

    assert app_path.read_text(encoding="utf-8") == before
